// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBANfdFo80r7CmOi1VwsrI3j16lcfhsGp4',
    appId: '1:203936488842:web:7395da74225d307c6cbc73',
    messagingSenderId: '203936488842',
    projectId: 'mynotes590',
    authDomain: 'mynotes590.firebaseapp.com',
    storageBucket: 'mynotes590.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdoYUWMJ_vkpOD7Vj1JrQ0cwNiwea6naM',
    appId: '1:203936488842:android:2a91e658053bb6576cbc73',
    messagingSenderId: '203936488842',
    projectId: 'mynotes590',
    storageBucket: 'mynotes590.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwxrSWdYLjNdi-5v6Q5j3qtiKJs9PsAmY',
    appId: '1:203936488842:ios:26c138fe4734f61f6cbc73',
    messagingSenderId: '203936488842',
    projectId: 'mynotes590',
    storageBucket: 'mynotes590.appspot.com',
    iosClientId: '203936488842-mhh0fr5uq2areerlqfnren3jhfdv4fpk.apps.googleusercontent.com',
    iosBundleId: 'com.ruvidev.mynotes',
  );
}
